### ISSUE TITLE
NBN Technology: undefined error for Tasmanian premises

### ISSUE THREAD

**Issue by BK1233** [LukePrior/nbn-availability-extension#2]
Hey Luke,

Thanks for making this extension!

Over the last few weeks, I have noticed when looking at premises located in Tasmania, they all come up with an NBN Technology: undefined error message. I will leave an example below and a link to a home for sale. 

For reference, I also use another extension for checking NBN technology types. https://chrome.google.com/webstore/detail/nbn-availability-checker/dphlehoebkdjgennbalpfpjnhjojcceo

https://www.realestate.com.au/property-house-tas-lenah+valley-139096555

![Screenshot_28](https://user-images.githubusercontent.com/12680340/165675143-3f87194f-8ad0-4ac6-8487-59e6c3d792ce.png)

**Comment by LukePrior** [comment]
Thanks for the report I'll have a look into what's causing this and see if I can find a solution.

**Comment by LukePrior** [comment]
Note to myself the API manages to match the address to a LocID `LOC000015981077` using the NBN address resolution API.

The error occurs with the MyRepublic API and appears to be due to MyRepublic not servicing any locations in Tasmania.

The API should fallback to the Uniti Wireless API where it would find that the address is in fact serviced by the NBN.

I think the issue is that as the MyRepublic API isn't returning an error and just a response of

`{"technology":null}`

that the fallback isn't triggered.

The best immediate fix will be to add a case to accommodate this fallback.

I am hoping to revise the API in future to use a more robust source but that is likely still a ways away.

**Comment by LukePrior** [comment]
Ok, that has been implemented with the extension now showing Unkown instead of undefined:

![image](https://user-images.githubusercontent.com/22492406/167849915-9c58cd21-ff67-49ad-ae8f-cf8a76a031c8.png)

As previously mentioned I will need to wait for a new API until this can be properly resolved so I will leave this issue open.

**Comment by Hongie84** [comment]
Hi Luke, Great extension.

Is there a way to display the NBN status on the initial realestate.com list page, rather than only on the individual listing?

**Comment by LukePrior** [comment]
Hi @Hongie84,

I'm glad you like the extension. I currently support the saved property pages for real-estate.com.au and domain.com.au. Is this what you were looking for on the homepage?

**Comment by Hongie84** [comment]
Hey I wasnt expecting a reply that quick.

I'm talking about on the search list. I will attach a screenshot to show
you where.
I had used a different extension that was displaying it on this page, and
it has stopped working now, I imagine realestate.com has changed something?

regards
Brad

[image: image.png]

**Comment by LukePrior** [comment]
Ok, I will look into adding that.

Notes to self:

- fix realestate.com.au single page display
- use list view for search page
